language: android

jdk:
  - openjdk11

env:
  global:
    - ANDROID_API=28
    - ANDROID_BUILD_TOOLS=28.0.3

android:
  components:
    - android-$ANDROID_API
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - platform-tools

branches:
  only:
  - master
