language: android

android:
  components:
    - build-tools-28.0.3

before_install:
  - mkdir -p "$ANDROID_SDK/licenses"
  - echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_SDK/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_SDK/licenses/android-sdk-preview-license"
