language: android

jdk:
  - openjdk11

before_install:
  - sudo mkdir -p "$ANDROID_SDK/licenses"
  - echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_SDK/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_SDK/licenses/android-sdk-preview-license"

env:
  global:
    - ANDROID_BUILD_TOOLS=28.0.3

android:
  components:
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - platform-tools

branches:
  only:
  - master
